name: Exploring GitHub Enterprise Action Features/Policies

on:
  push:
  workflow_dispatch:

jobs:
  demo_job:
    runs-on: self-hosted
    steps:
      - name: Hello
        run: echo "Hello GitHub Enterprise!!"
        
      - name: External Call using cURL
        run: curl -v http://httpbin.org/ip
